### ISSUE TITLE
How do we instruct users obtain example dataset and Rmd files?

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#100]
Some users are intimidated by Github. It is not very clear how one can get individual notebooks, either from the repo or the rendered HTML R notebook. 

We had talked about having a script to upload them to s3 on commit to master for a different script. That could be an option.

Explore other possible solutions so it is simpler for people to get individual notebooks.

The band-aid fix for this would be to explicitly mention in the docs and README how to get these individual notebooks.

**Comment by cansavvy** [comment]
Our current alternative to this is writing more explicit, step-by-step instructions on how to download files files from refinebio at the introduction to each analysis.

**Comment by cansavvy** [comment]
Some alternative ideas: 
- Can we include a basic folder set up with an Rmd download? 
- Can we zip up each of the analyses folders (data included) and allow users to download them from S3?

**Comment by cansavvy** [comment]
For now we are moving forward with the step-by-step instructions for download. This is drafted out on #146 

This seems like the best approach for now because: 
- this will also teach users how they can download other datasets as they begin to tailor an example notebook to their own needs. 
- No S3 storage links needed. 

This is a main component of what we will wanting to test on #145 . If it turns out that this strategy is not working, then we can revisit the issue.
