### ISSUE TITLE
[Discussion/Idea] One dataset for each technology section?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#114]
Related: #102 

Would we be able to use one microarray dataset for the microarray section and one for the RNA-seq section and etc? 

I think this would be easier for users to keep track of rather than having a new dataset to work with for each example. This would allow us to just have once in each section that we would more slowly guide the user through how to obtain the dataset from refinebio and set it up. 

I don't know how this would effect the pathway analyses. 

How would the datasets we used for the respective DE modules work? Here's their refinebio links: 
For RNA-seq : https://www.refine.bio/experiments/SRP078441/rna-seq-of-primary-patient-aml-samples
For microarray: https://www.refine.bio/experiments/GSE71270/creb-overexpression-induces-leukemia-in-zebrafish-by-blocking-myeloid-differentiation-process

**Comment by jaclyn-taroni** [comment]
I'm not sure one dataset per technology meets our goal of having an analysis module be pretty self-contained.

**Comment by cansavvy** [comment]
This seems like it would be tiresome to the type of reader who is following through more than one example to go through how to download a new dataset for each example.

**Comment by jaclyn-taroni** [comment]
I think it's less likely to be tiresome if you use different datasets.

**Comment by jaclyn-taroni** [comment]
If someone is inclined to go through multiple or all examples, I expect they are more likely to read "getting started" where we can prepare them for this repetition by explaining that they are also designed to be standalone. I meant using different datasets is likely to be a little more interesting if you're going through multiple or all experiments in my last comment. Thoughts @dvenprasad?

**Comment by cansavvy** [comment]
I'm just having trouble making plans that fit both the "keep it modularized" and the "make it follow along" (#101).

**Comment by jaclyn-taroni** [comment]
> I'm just having trouble making plans that fit both the "keep it modularized" and the "make it follow along" (#101).

We should see if everyone's understanding of "make it follow along" is the same. What do you think it means? My impression is that it means that we need considerably more context for each example and the packaging needs to be more coherent than a GitHub repository alone can offer. It does not mean we necessarily need to craft an entire series of an analysis for a single dataset. But we should get @dvenprasad to weigh in because she filed #101!

**Comment by dvenprasad** [comment]
It is hard to strike the balance between follow-along and keeping it modular enough that people can dip in and out of the different examples. 

Primarily, I think these examples should be modular, i.e people can drop in the middle and still have sufficient context to quickly orient themselves. Follow-along in the context of the issue I filed, I meant follow-along within a type of analysis. Something along the lines of `"Here's this notebook, here's the data, here's what we're doing in the notebook. You should see this when run stuff. You can point it to a different refine.bio dataset if you want. Try it in the notebook you setup!"` for each analysis type (i.e differential expression, or converting to ensmbl ids) 

In this case, we would ask them to get the data for the example at the beginning of every analysis type. Whether we want to link to different dataset each time, I'll leave it up you folks to decide. If there is benefit is choosing a different dataset because it would better illustrate the nuances of a method, it is okay. (here I'm assuming that the notebooks can be used with a different refine.bio dataset if they want?) 

Can the folks who are following the examples sequentially still choose to use a dataset from the previous examples and things would not go awry? Would it be hard to set it up in that way? (This is a nice to have.... if it is too hard, happy to give it the axe)

**Comment by jaclyn-taroni** [comment]
>In this case, we would ask them to get the data for the example at the beginning of every analysis type. Whether we want to link to different dataset each time, I'll leave it up you folks to decide. If there is benefit is choosing a different dataset because it would better illustrate the nuances of a method, it is okay. (here I'm assuming that the notebooks can be used with a different refine.bio dataset if they want?)

Yes, I think it will often be the case that a different dataset would better illustrate the use of a method.

> Can the folks who are following the examples sequentially still choose to use a dataset from the previous examples and things would not go awry? Would it be hard to set it up in that way? (This is a nice to have.... if it is too hard, happy to give it the axe) 

The problem are, per usual 😅 , the metadata or sample labels. If you are grouping samples together for an analysis (e.g., DGE), what you'll use to do that grouping will change from dataset to dataset and it won't always be appropriate to use the same methods on any given dataset you get from refine.bio. I would think we may need sufficient explanation of when some method or approach is appropriate to use. That's not typically been how our examples are designed (something like `pathway-analysis` has more context than others, though).

**Comment by cansavvy** [comment]
So I think we should stick with the datasets we have for the analyses so far. Thanks for this guidance, @dvenprasad and @jaclyn-taroni. I'm going to start to make a plan for what each analysis' structure should look like. See #116 I figure the more parallel we can make the structure of all the analysis example, the better. My idea is that a good structure should help users who are using more than one example know what to expect in each (and can skip if they want), but then there should still be adequate context for the user who has cherry picked one example. Does this make sense/sound good?

**Comment by jaclyn-taroni** [comment]
> My idea is that a good structure should help users who are using more than one example know what to expect in each (and can skip if they want), but then there should still be adequate context for the user who has cherry picked one example. Does this make sense/sound good?

Yes, sounds good. I think "Getting started" (#109) should explain why we've set things up this way/what to expect per the comment above:

> If someone is inclined to go through multiple or all examples, I expect they are more likely to read "getting started" where we can prepare them for this repetition by explaining that they are also designed to be standalone.

**Comment by cansavvy** [comment]
> If someone is inclined to go through multiple or all examples, I expect they are more likely to read "getting started" where we can prepare them for this repetition by explaining that they are also designed to be standalone.

I've added this to the rough outline in #109 Going to close this issue now because sounds like we have plans moving forward.
