### ISSUE TITLE
Microarray Analysis Updates: clustering heatmap

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#181]
Besides the up to date steps listed #173 :

> - Have the getting started template material added to it(# 146)
> - Be updated to adhere to the style guide (#148)
> - Add dataset to S3 buckets.
> - Be added to the Snakefile and rendered with snakemake on the Docker container.

It also needs to have its dataset here (which is n = 4) switched to one with a bigger sample size. 
For the heatmap creation steps, we should also mirror the set up that's used over on rnaseq clustering notebook (make an unannotated heatmap first, then make the annotation data.frame, then make an annotated heatmap).

**Comment by cbethell** [comment]
In searching for a larger dataset to use in this notebook as mentioned above, I found the following tentative datasets:

[PTEN loss defines a PI3K/AKT pathway-dependent germinal center subtype of diffuse large B-cell lymphoma](https://www.refine.bio/experiments/GSE45495/pten-loss-defines-a-pi3k-akt-pathway-dependent-germinal-center-subtype-of-diffuse-large-b-cell-lymphoma)
<img width="710" alt="Screen Shot 2020-09-01 at 8 38 25 PM" src="https://user-images.githubusercontent.com/43576623/91924457-ba230080-eca0-11ea-9ca3-7fc90b23b11e.png">

This dataset seems like it may be a bit more complex than the below dataset because the treatment given was also associated with time. According to the supplemental methods from the [associated paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3725065/):
```
HT cells were transduced with PTEN cDNA and selected with puromycin, 
and PTEN cDNA expression was induced with doxycycline; 6, 12, 18, and 24 h after PTEN induction.
```

[Expression data from melanoma cell lines](refine.bio/experiments/GSE24862/expression-data-from-melanoma-cell-lines)
<img width="658" alt="Screen Shot 2020-09-01 at 10 14 04 PM" src="https://user-images.githubusercontent.com/43576623/91924478-cd35d080-eca0-11ea-9886-700186674946.png">

This dataset appears to have information on 21 samples taken from 6 unique cell lines (multiple samples resulting from replicates for each of the 2 treatment scenarios for each cell line).

Are there any thoughts on whether or not one of these datasets would be better suited for the microarray clustering notebook revamp (or any strong feelings on why we should not use either)?

**Comment by cansavvy** [comment]
If we were to use PTEN, It looks like there are cell line samples and samples from patients? So I'd be interested in seeing how those cluster. I also find those samples on the very left very curious, it looks like the values are all very high or very low. But I think I agree with you, their experimental model has so much going on, it's a little hard to digest or make any kind of reasonable interpretation.  

I think I like `Expression data from melanoma cell lines` because the clustering seems to tell me how the cell lines used are probably a much bigger factor than the treatments (which is probably true more often than we'd like). 

What do you think, @cbethell ?

**Comment by cbethell** [comment]
> If we were to use PTEN, It looks like there are cell line samples and samples from patients? So I'd be interested in seeing how those cluster. I also find those samples on the very left very curious, it looks like the values are all very high or very low. But I think I agree with you, their experimental model has so much going on, it's a little hard to digest or make any kind of reasonable interpretation.
> 

Yes it is cell line samples and samples from patients (which I thought was interesting as well). However, what is quite interesting to us does appear to be a little complex for this notebook if we really want to accurately represent the data (which would mean also creating annotation for cell line samples vs patient samples).

> I think I like `Expression data from melanoma cell lines` because the clustering seems to tell me how the cell lines used are probably a much bigger factor than the treatments (which is probably true more often than we'd like).
> 
> What do you think, @cbethell ?

That being said, I agree with you here, I think I like the `Expression data from melanoma cell lines` dataset for this notebook.
