### ISSUE TITLE
Update RNA-seq gene id conversion module

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#213]
This needs to be brought up to speed with the CONTRIBUTING.md guidelines

> - Have the getting started template material added to it(# 146)
> - Be updated to adhere to the style guide (#148)
> - Have its dataset added to the S3 bucket. (See https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#adding-datasets-to-the-s3-bucket)
> - Be added to the Snakefile and rendered with snakemake on the Docker container.
> - Be evaluated for any content changes that we may have updated thoughts on (this one we will have to determine analysis by analysis)

- I think we should add a few quick steps in the vein of "look at your data" that explore how the mapping from gene identifier conversions went. This can largely be parallel to #113
- As discussed on #174, we want this module to be parallel but model different aspects than its microarray counterpart. This means at least a different species and different gene identifier, but we may want to think about if there's something else we should model. 
- Since this is a cross-technology module (#174) we should probably have a link to the microarray notebook and tell the users that even thought its a different technology, the steps are cross-tech compatible and they can reference the other notebook for a second example.

**Comment by cbethell** [comment]
In reference to @cansavvy's [comment](https://github.com/AlexsLemonade/refinebio-examples/pull/218#discussion_r490386991) on PR #218, I found some tentative datasets that can be used to replace the one in that PR and would appreciate some feedback on which one we should settle on!

1. [Gene expression analysis of hair cell regeneration in the zebrafish lateral line](https://www.refine.bio/experiments/SRP040561/gene-expression-analysis-of-hair-cell-regeneration-in-the-zebrafish-lateral-line#samples)

This dataset has 24 samples. From the [associated paper](https://pubmed.ncbi.nlm.nih.gov/24706903/), the goal of the experiment is as follows:

"Deafness caused by the terminal loss of inner ear hair cells is one of the most common sensory diseases. However, nonmammalian animals (e.g., birds, amphibians, and fish) regenerate damaged hair cells. To understand better the reasons underpinning such disparities in regeneration among vertebrates, we set out to define at high resolution the changes in gene expression associated with the regeneration of hair cells in the zebrafish lateral line. We performed RNA-Seq analyses on regenerating support cells purified by FACS."

2. [Parental exposure to gamma radiation causes progressively altered transcriptomes that are linked to adverse effects in zebrafish offspring](https://www.refine.bio/experiments/SRP106454/parental-exposure-to-gamma-radiation-causes-progressively-altered-transcriptomes-that-are-linked-to-adverse-effects-in-zebrafish-offspring).

This dataset has 14 samples. From the [associated paper](https://pubmed.ncbi.nlm.nih.gov/29248853/), " Here, we assessed short (one month) and long term effects (one year) on gene expression in embryonic offspring (5.5 h post fertilization) from zebrafish exposed during gametogenesis to gamma radiation (8.7 or 53 mGy/h for 27 days, total dose 5.2 or 31 Gy) using mRNA sequencing."

Both datasets are similar in number of NAs and number of multi mappings found, but the first dataset has the larger file at the end due to more samples.

Which do we think is best suited for this purpose?

**Comment by cansavvy** [comment]
> Which do we think is best suited for this purpose?

Either is fine for gene conversion, as we mentioined. 🤷‍♀️ 

But neither have much metadata if users wanna play with it (a known problem for the RNA-seq data that's being worked on by Steven). But of the two, the first one has information in the `refinebio_title` at least. So I guess I'd go with that one.
