### ISSUE TITLE
[Discussion] How different does a new example need to be from the existing example to be added?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#223]
Related to #219 

For us to add a new module, how different does it have to be from the existing example? Not sure how to quantify this, but I think its something we should figure out before I potentially implement #219.

Using #219 as an example, this new module would diiffer from the existing differential expression microarray module by: 
- Steps to deal with the outlier
- Steps of providing a 3 group DE (as opposed to 2)
- It's a different species (Not sure that this actually changes the steps).
- The interpretation would be different. 

This discussion goes hand in hand with what aspects of an analysis are critical to show in an example and which do we figure users can "figure out on their own".

**Comment by jaclyn-taroni** [comment]
Would you need to necessarily decide before you implement #219? My understanding of our current concept of modules is that is captured in filename only. So I can imagine a situation where writing the bare bones of example itself could clear things up wrt deciding to go for a new module.

**Comment by cansavvy** [comment]
> bare bones of example itself could clear things up wrt deciding to go for a new module.

Can you say more about this part? What would you consider the "bare bones"? I started writing #219, and IMO, it's different "enough" but I guess what this issue is about is how distinct do we want our examples to be? Or will we always just take this case by case? (I imagine the answer to my second question here is always to some extent yes).

**Comment by jaclyn-taroni** [comment]
Now with your reply (and looking again at the title of the issue) I think you're using the terms `module` and `example` interchangeably in your initial comment:

> For us to add a new module, how different does it have to be from the existing example? Not sure how to quantify this, but I think its something we should figure out before I potentially implement #219.
> 
> Using #219 as an example, this new module would diiffer from the existing differential expression microarray module by:

Where we used to use the term `module` to refer to the folder structure and now in the [section about new analyses in CONTRIBUTING](https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#setting-up-a-new-analysis-file) says `<analysis-module>_<section/tech>_<notebook#>_<name-of-analysis>.Rmd`. 

So my point in https://github.com/AlexsLemonade/refinebio-examples/issues/223#issuecomment-695075068 was it is not necessary to decide if something would be a new module ahead of time, because the only way we capture the notion of a module now is the file name and other things that are easily changed. 

Now with https://github.com/AlexsLemonade/refinebio-examples/issues/223#issuecomment-695087219, I think the question in your title:

> How different does a new example need to be from the existing example to be added?

Could also be asked in a more general sense as, "How do we know when to add a new example?" And I think your _more specific_ question is, "How do we decide if something is in scope for this project?" 

In my opinion, to answer both questions, we should first ask ourselves a series of questions:

- Is the addition valuable to our users?
- Do we have what we need to create and maintain an addition consistent with the quality of the rest of the project? (Usually for this project this will be in terms of people time rather than resources like compute.)
- How does the potential value to our users for the addition compare to other things we would like to accomplish (add, update, etc.)? (That will tell us about priority.)
