### ISSUE TITLE
Prettier/better diagrams showing how RNA-seq/microarray work

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#255]
Based on @envest's request for moar worfklow graphics, I searched the internet for useful diagrams, and was only kind of successful: https://github.com/AlexsLemonade/refinebio-examples/pull/232#issuecomment-701477282

I found some placeholder figures that will work for now and illustrate the basic point of what we want in our rnaseq and microarray section headers, but they are not great looking, and also pretty low res. 

It would be good for us to make some nice workflow diagrams that explain the basic concepts behind the technologies that would be higher res and be more aesthetically pleasing. They should follow whatever color palette is used for #199 

The current, not great figures: 

https://github.com/AlexsLemonade/refinebio-examples/raw/13fd8c2d8469f2ac35e1608b4a952a5f5fe9698c/components/figures/microarray-overview.jpg

https://github.com/AlexsLemonade/refinebio-examples/raw/13fd8c2d8469f2ac35e1608b4a952a5f5fe9698c/components/figures/rnaseq-overview.png

**Comment by cbethell** [comment]
Here's my first attempt at revamping the microarray diagram:

<img width="1250" alt="microarray" src="https://user-images.githubusercontent.com/43576623/96459942-adc31a80-11f0-11eb-8e6f-b27b6318d290.png">

Is this similar to what we had in mind? It is heavily based on the current linked diagram (and should probably cite it) because I believe that diagram did a good job at breaking down the process, but this can be changed if this isn't what we want. (I am aware that I am not the best graphic designer so please feel free to leave absolutely any and all suggestions!)

**Comment by cbethell** [comment]
Here's my first attempt at revamping the microarray diagram:

<img width="1260" alt="microarray" src="https://user-images.githubusercontent.com/43576623/96460898-b9fba780-11f1-11eb-935f-6b6c38ac05ad.png">


Is this similar to what we had in mind @cansavvy? It is heavily based on the current linked diagram (and should probably cite it) because I believe that diagram did a good job at breaking down the process, but this can be changed if this isn't what we want. (I am aware that I am not the best graphic designer so please feel free to leave absolutely any and all suggestions!)

**Comment by cansavvy** [comment]
> Is this similar to what we had in mind @cansavvy? It is heavily based on the current linked diagram (and should probably cite it) because I believe that diagram did a good job at breaking down the process, but this can be changed if this isn't what we want. (I am aware that I am not the best graphic designer so please feel free to leave absolutely any and all suggestions!)

I should have made this point originally on this issue: refine.bio doesn't handle two color array platforms, so we want this diagram to focus on one-color array. (I couldn't find a diagram that only focused on one-color that looked presentable).
So basically get rid of the two samples part and only have the one sample that hybridizes. 

But otherwise this looks good to me. Just need to delete the two color referencing bits.

**Comment by cbethell** [comment]
> > Is this similar to what we had in mind @cansavvy? It is heavily based on the current linked diagram (and should probably cite it) because I believe that diagram did a good job at breaking down the process, but this can be changed if this isn't what we want. (I am aware that I am not the best graphic designer so please feel free to leave absolutely any and all suggestions!)
> 
> I should have made this point originally on this issue: refine.bio doesn't handle two color array platforms, so we want this diagram to focus on one-color array. (I couldn't find a diagram that only focused on one-color that looked presentable).
> So basically get rid of the two samples part and only have the one sample that hybridizes.
> 
> But otherwise this looks good to me. Just need to delete the two color referencing bits.

What do you think of the changes I made in the figure below @cansavvy? Does this better represent the one-color array?

<img width="822" alt="microarray-take2" src="https://user-images.githubusercontent.com/43576623/96494557-854d1780-1214-11eb-8819-5f9af1a18ec8.png">

I've also copied most of the general structure of the current RNA-seq diagram: https://github.com/AlexsLemonade/refinebio-examples/raw/13fd8c2d8469f2ac35e1608b4a952a5f5fe9698c/components/figures/rnaseq-overview.png

However, I wanted to find out if there were any other general changes we would like to include here before completing the RNA-seq diagram.

**Comment by cansavvy** [comment]
I think these look great! We will still want to give credit to the original diagrams ("based on..."). 

I honestly don't have any comments about the images in particular. When you add them to the intros, we may want to add more words to briefly summarize what these respective diagrams are showing.

**Comment by cansavvy** [comment]
I wonder if in the RNA-seq one, if we should only mention tissue (remove the `isolated cell` biit) since currently refine.bio doesn't specifically support single cell (except sort of Smart-seq2 stuff).

**Comment by cansavvy** [comment]
One more thought, we may want to change the image for the `Image analysis` bit in the microarray diagram since it doesn't really tell us much beyond what we know. Aka maybe show how fluorescence intensity is converted to values?

**Comment by cbethell** [comment]
> I think these look great! We will still want to give credit to the original diagrams ("based on...").
> 
> I honestly don't have any comments about the images in particular. When you add them to the intros, we may want to add more words to briefly summarize what these respective diagrams are showing.

I'm about to start working on preparing the PRs for to get these images along with context in the appropriate sections of the repo. In the meantime, does the following updated images reflect the suggestions you made in the last 2 comments on this issue @cansavvy?

<img width="777" alt="Screen Shot 2020-10-22 at 9 13 31 AM" src="https://user-images.githubusercontent.com/43576623/96877119-3f2bca00-1447-11eb-9200-44e6df53a8dd.png">

For this diagram, I did some googling to find typical values obtained to represent fluorescence intensity and the general consensus was that numeric values are assigned that would then be proportional to the gene expression values. I tried to keep the diagram as simple as possible but would not want lose correctness so please let me know if you believe that I portrayed the image analysis interpretation incorrectly.

<img width="309" alt="Screen Shot 2020-10-22 at 9 13 59 AM" src="https://user-images.githubusercontent.com/43576623/96877122-40f58d80-1447-11eb-9df4-18d0a5e2be99.png">

Tagging @dvenprasad here because it would be great to get your thoughts on these images as well!

**Comment by dvenprasad** [comment]
These look good to me in structure and layout. Also it looks visually unified with refinebios palette!  🎉 

I have a question: These arrows, are they arrows between the steps? 

<img width="717" alt="Screen Shot 2020-10-22 at 9 47 14 AM" src="https://user-images.githubusercontent.com/15315514/96880791-96339e00-144b-11eb-92cc-7dc77bfcccae.png">

The only thing that bothers me (100% nitpicking, does not effect comprehension at all) is the space between `Raw image of channel` and the plate in the first image below is too little, almost looks like it is sticking to it. The same with `Isolate specific RNA species` and  the line below in the second image.

**Comment by cbethell** [comment]
> I have a question: These arrows, are they arrows between the steps?
> 
> <img alt="Screen Shot 2020-10-22 at 9 47 14 AM" width="717" src="https://user-images.githubusercontent.com/15315514/96880791-96339e00-144b-11eb-92cc-7dc77bfcccae.png">

@dvenprasad Yes, there are arrows between steps. Should they be placed differently to make that a bit more clear? 

> The only thing that bothers me (100% nitpicking, does not effect comprehension at all) is the space between `Raw image of channel` and the plate in the first image below is too little, almost looks like it is sticking to it. The same with `Isolate specific RNA species` and the line below in the second image.

Ah I see, no worries, I can definitely fix that!

**Comment by dvenprasad** [comment]
Ah i was thinking maybe having a vertical bolder arrow centered between the steps would be clearer? Like this maybe? Would it still retain meaning?

<img width="1339" alt="Screen Shot 2020-10-22 at 10 44 29 AM" src="https://user-images.githubusercontent.com/15315514/96888437-a0599a80-1453-11eb-9fba-d55938f42d9e.png">

**Comment by cbethell** [comment]
> Ah i was thinking maybe having a vertical bolder arrow centered between the steps would be clearer? Like this maybe? Would it still retain meaning?
> 
> <img alt="Screen Shot 2020-10-22 at 10 44 29 AM" width="1339" src="https://user-images.githubusercontent.com/15315514/96888437-a0599a80-1453-11eb-9fba-d55938f42d9e.png">

I believe these arrows allow for the meaning to still be retained 👍
