### ISSUE TITLE
Ask users to replace paths to data when defining variables

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#269]
![Screen Shot 2020-10-05 at 10 14 30 PM](https://user-images.githubusercontent.com/15315514/95151266-3bfec180-0758-11eb-9ba9-a30ea8631175.png)

Can we add `#Replace with path to your metadata file` here? Also define metadata_file name and data file name? 

I'm thinking that if there is only one spot the users will need to update if they are using a different dataset, instead of every spot downstream, less likely they are to make mistakes. Also they will be able to catch if they have pointed it to an invalid path.

We should add a note saying modify the file paths if using a different dataset, and link them back to this chunk, in the downstream chunks.

**Comment by cansavvy** [comment]
I have a couple thoughts on this that may have incorrect assumptions about how users work.

The main concern is that when users click on the `Jump to the analysis` code bit that they would miss the part where we assigned the file path to a variable and I'm not sure where we would put the assignment and have it still be useful but not have them miss that. 

We've created the getting started section material so that it can be all deleted if the user wants to and nothing is actually affected (but they have to have their files in the right place). If we assign the dataset, the getting started material would then become a necessary step in the analysis.

**Comment by cansavvy** [comment]
@dvenprasad and I talked it out and figured out what I think is a good solution, we can declare the file paths earlier in the getting started secetion and then when we use them to read in the file we have a link to where we declared them (for those users who may have rushed through or used the "Jump to analysis code" button. 

This way people who missed it can go back and see where we declared it but users also will only need to change it in one spot for when they try to use a different refine.bio dataset with the analysis.
