### ISSUE TITLE
Move References section

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-examples#275]
The Reference section gets a bit lost below the (very long) Session Info section.

I would propose we move them above it, and give them their own header. Even if we don't move them up, we should give them a header!

We might want to make References and Session Info subheadings of some other heading, but I don't feel strongly about this.

**Comment by cansavvy** [comment]
I don't want to move the references section above the session info because then users may miss the session info bit which is a good practice we want them to see (and run that chunk). However, I am going through and adding "References" headers which does add "References" to the scrolling ToC on the side, does this seem acceptable to you, @jashapiro ?
