### ISSUE TITLE
Visual Unity: Make refine.bio-examples footer

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#279]
I don't know how difficult this is to do, but if we can add a footer that is like refine.bio's footer, that would help people cite us as well as help them navigate to other things: https://www.refine.bio/

This is definitely doable but how painful it is to make it exactly like refine.bio's footer I do not know. 

https://stackoverflow.com/questions/25329375/creating-a-footer-for-every-page-using-r-markdown

This _shouldn't_(?) have to change for every example like the `_navbar.html` does so it shouldn't add to upkeep burden. I think we should be able to add a footer to the header of each example and then the rest should be automatic. I haven't tested this though.

**Comment by cansavvy** [comment]
We also might want to move the refine.bio and GitHub links to the footer. We will need the survey link prominently at the top and currently its a bit crowded on the navbar otherwise.

**Comment by jashapiro** [comment]
We will probably want to accomplish this with a `footer.html` file in `components/`  which we can include as described in 
https://bookdown.org/yihui/rmarkdown/html-document.html#includes

More specifically, since we want to keep the Rmd files able to render without modification, these will be passed to [`html_document`](https://www.rdocumentation.org/packages/rmarkdown/versions/2.4/topics/html_document) in the rendering script, using [`includes`](https://www.rdocumentation.org/packages/rmarkdown/versions/2.4/topics/includes) to put things in the header or footer as appropriate.

**Comment by jashapiro** [comment]
> We also might want to move the refine.bio and GitHub links to the footer. We will need the survey link prominently at the top and currently its a bit crowded on the navbar otherwise.

I would argue for keeping refine.bio in the header, but github to the footer makes sense to me!
