### ISSUE TITLE
Visual Unity: refinebio-examples font and colors made more like refine.bio

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#282]
This is _fairly_ straightforward to do. We already render our notebooks through `render-notebooks.R` and the `rmarkdown::html_document()` can be given a `css` argument. 

I already tested this out and have a basic framework that works set up [on this branch](https://github.com/AlexsLemonade/refinebio-examples/tree/cansavvy/refinebio-fashion). 

Second step is to make that styles.css file conform to the refine.bio style guide here: https://github.com/AlexsLemonade/refinebio-design/blob/master/styleguide-dev.pdf

This is less clear to me what the most straightforward way to do this is.

**Comment by jashapiro** [comment]
Noticed in #246, we should make sure our code chunks don't wrap arbitrarily. While we should strive to keep our lines short, in a narrow window, we may still result in odd line breaks that impair readability of code. 

 To fix this I think we will need to define CSS for the `<code>` blocks with `white-space: pre` rather than `pre-wrap` which seems to be what they get now.

**Comment by cansavvy** [comment]
Closed by #303

**Comment by cansavvy** [comment]
Also superceded by #323
