### ISSUE TITLE
Microarray: Pathway Analysis - GSEA

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#284]
As a part of the pathway analysis module, we should add a GSEA example for microarray data. 

There's a lot of docs from the broad we can reference: https://www.gsea-msigdb.org/gsea/index.jsp

We can use the differential expression results from either `differential-expression_microarray_01_2-groups.Rmd` or `differential-expression_microarray_02_several-groups.Rmd`.

We can borrow some inspiration from https://github.com/AlexsLemonade/training-modules/blob/master/pathway-analysis/02-gene_set_enrichment_analysis.Rmd

**Comment by cbethell** [comment]
Per discussion with @cansavvy, the current plan for this issue is as follows:

1. Load in packages (`clusterProfiler` to run GSEA, `msigdbr` and species annotation package)
2. Import the results from this repo's `differential-expression_microarray_01_several-groups.Rmd` (note that this is tentative to change based on how the visualization of the GSEA results for this dataset looks later on in the example)
3. Like in the updated ORA example, we can include the [“getting familiar with `clusterProfiler`'s options"](https://github.com/AlexsLemonade/refinebio-examples/blob/36b81e881afd50f2760122495de142039233183f/02-microarray/pathway-analysis_microarray_02_ora.Rmd#L184) section
4. Like in the training modules GSEA example, include a [section on isolation of hallmark genes](https://github.com/AlexsLemonade/training-modules/blob/3dbc6f3f53c680ec6aa2f513851c1cd4635cc31c/pathway-analysis/02-gene_set_enrichment_analysis.Rmd#L90) with a note saying something along the lines of: "if you want a more curated dataset, run this chunk" (whether or not we keep this chunk may depend on processing time and length of the notebook; we may replace the chunk with a sentence or two re using hallmark genes to generate a curated dataset)
5. Perform gene identifier conversion (using the `mapIds()` function)
6. Determine genes of interest list (using log fold change and possibly adjusted p-value as cutoffs -- decision will likely be made based on number of significant results found and visualizations)
7. Perform gsea using `GSEA()` function from `clusterProfiler` providing the genes of interest list to the `geneList` argument -- note that discretion may also be used here with the number of permutations based on processing time (we want to keep processing time to a minimum for our users but without losing an important aspect of the analysis)
8. Preview any significant results using adjusted p values as the cutoff like in the [ORA example](https://github.com/AlexsLemonade/refinebio-examples/blob/36b81e881afd50f2760122495de142039233183f/02-microarray/pathway-analysis_microarray_02_ora.Rmd#L405)
9. Preview how the highly negative and positive enrichment scores are determined then visualize them using `enrichplot::gseaplot()`
10. Save plots like in the ORA example
11. Write GSEA results to file
12. Link some resources from https://www.gsea-msigdb.org/gsea/index.jsp in the resources section

A draft PR implementing the above plan will be filed for a high-level overview in accordance with what's on the relevant improving the PR review process discussion ticket #295.

**Comment by cbethell** [comment]
This issue was closed by merged PR #347.
