### ISSUE TITLE
Editing: Someone needs to look at the GitHub Pages version of all examples and file issues

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#289]
The HTML versions of examples that can be browsed via the GitHub Pages will be different from development (`html_document` vs. `html_notebook`). As a result, there may be somethings like printing out large data frames that do not work particularly well in that context. We should have someone go through the entire site and make notes.

**Comment by jashapiro** [comment]
I'm putting this here, as it seems the most reasonable place, rather than as a new issue: 

We may want to consider making blocks with `library()` calls include `message = FALSE` to avoid chatty outputs cluttering the page. (DESeq2 👀 )

We could also do this on a global basis, with `knitr::opts_chunk$set(message = FALSE)` early on in the doc, but it probably makes sense to keep this on a case by case basis.

**Comment by jashapiro** [comment]
One particular issue that came up as I started review with some of these thoughts in mind: how do we feel about the output of `readr::read_tsv()`? Do we want to suppress this in general?

Original comment:
https://github.com/AlexsLemonade/refinebio-examples/pull/409#issuecomment-738246954

**Comment by jaclyn-taroni** [comment]
@jashapiro are we good to close this (and #290)? Last GSVA PR is imminent (and tracked via #371 and #349 arguably).

**Comment by jashapiro** [comment]
I think we can close it. I'm sure we will catch things later, but individual issues seem to be the way to go now.
